###DISPONIBILIDAD
POST http://localhost:8080/reyCanino/consultar
content-type: application/json

{
    "fechaConsulta":"2021-03-20T05:00:00.000Z",
    "servicio":"1",
    "tiendaCanina":"f27d9717-9f4c-4ad2-ae36-8e9117b3848e"

}

###Reservar
POST http://localhost:8080/reyCanino/reservar
content-type: application/json

{
    "id":"56fcb644-c656-4a99-97b0-561fd106de18",
    "reserva":{
        "cliente":"038e2c41-e374-4770-9331-6861550d9427",
        "nombreMascota":"Tomas1",
        "razaMascota":"Shih Tzu"
    },
    "tiendaCanina":"f27d9717-9f4c-4ad2-ae36-8e9117b3848e"
}

###Confirmar
GET http://localhost:8080/reyCanino/confirmar/de3fd7e6-1713-4d9b-9ad7-9559168e6178


###Consultar reserva
GET http://localhost:8080/reyCanino/consultar/de3fd7e6-1713-4d9b-9ad7-9559168e6178

###Consultar horario
GET http://localhost:8080/reyCanino/horario/038e2c41-e374-4770-9331-6861550d9427

### Consultar horario Admin
GET http://localhost:8080/reyCanino/horarioAdmin/f27d9717-9f4c-4ad2-ae36-8e9117b3848e

###Login
POST http://localhost:8080/reyCanino/login/
content-type: application/json

{
    "correo":"mafehv1999@hotmail.com",
    "psw":"03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
}


### horario cliente
GET http://localhost:8080/reyCanino/horario/038e2c41-e374-4770-9331-6861550d9427	
